# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {Common-41} -limit 4294967295
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Sophomore/ECOP-2018/ECOP-17343155-03/CPU_imp/CPU_imp.cache/wt [current_project]
set_property parent.project_path D:/Sophomore/ECOP-2018/ECOP-17343155-03/CPU_imp/CPU_imp.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  D:/Sophomore/ECOP-2018/ECOP-17343155-03/CPU_imp/CPU_imp.srcs/sources_1/new/DR.v
  D:/Sophomore/ECOP-2018/ECOP-17343155-03/CPU_imp/CPU_imp.srcs/sources_1/new/IR.v
  D:/Sophomore/ECOP-2018/ECOP-17343155-03/CPU_imp/CPU_imp.srcs/sources_1/new/regWriteData.v
  D:/Sophomore/ECOP-2018/ECOP-17343155-03/CPU_imp/CPU_imp.srcs/sources_1/new/regWriteAddress.v
  D:/Sophomore/ECOP-2018/ECOP-17343155-03/CPU_imp/CPU_imp.srcs/sources_1/new/regFile.v
  D:/Sophomore/ECOP-2018/ECOP-17343155-03/CPU_imp/CPU_imp.srcs/sources_1/new/PC.v
  D:/Sophomore/ECOP-2018/ECOP-17343155-03/CPU_imp/CPU_imp.srcs/sources_1/new/nextPC.v
  D:/Sophomore/ECOP-2018/ECOP-17343155-03/CPU_imp/CPU_imp.srcs/sources_1/new/nextCondition.v
  D:/Sophomore/ECOP-2018/ECOP-17343155-03/CPU_imp/CPU_imp.srcs/sources_1/new/Jext.v
  D:/Sophomore/ECOP-2018/ECOP-17343155-03/CPU_imp/CPU_imp.srcs/sources_1/new/insROM.v
  D:/Sophomore/ECOP-2018/ECOP-17343155-03/CPU_imp/CPU_imp.srcs/sources_1/new/extend.v
  D:/Sophomore/ECOP-2018/ECOP-17343155-03/CPU_imp/CPU_imp.srcs/sources_1/new/Dtrigger.v
  D:/Sophomore/ECOP-2018/ECOP-17343155-03/CPU_imp/CPU_imp.srcs/sources_1/new/dataRAM.v
  D:/Sophomore/ECOP-2018/ECOP-17343155-03/CPU_imp/CPU_imp.srcs/sources_1/new/ControlUnit.v
  D:/Sophomore/ECOP-2018/ECOP-17343155-03/CPU_imp/CPU_imp.srcs/sources_1/new/ALU_dataB.v
  D:/Sophomore/ECOP-2018/ECOP-17343155-03/CPU_imp/CPU_imp.srcs/sources_1/new/ALU_dataA.v
  D:/Sophomore/ECOP-2018/ECOP-17343155-03/CPU_imp/CPU_imp.srcs/sources_1/new/ALU.v
  D:/Sophomore/ECOP-2018/ECOP-17343155-03/CPU_imp/CPU_imp.srcs/sources_1/new/show.v
  D:/Sophomore/ECOP-2018/ECOP-17343155-03/CPU_imp/CPU_imp.srcs/sources_1/new/Hex7seg.v
  D:/Sophomore/ECOP-2018/ECOP-17343155-03/CPU_imp/CPU_imp.srcs/sources_1/new/debouncing.v
  D:/Sophomore/ECOP-2018/ECOP-17343155-03/CPU_imp/CPU_imp.srcs/sources_1/new/CLK_DIV.v
  D:/Sophomore/ECOP-2018/ECOP-17343155-03/CPU_imp/CPU_imp.srcs/sources_1/new/CPU_top.v
  D:/Sophomore/ECOP-2018/ECOP-17343155-03/CPU_imp/CPU_imp.srcs/sources_1/new/imp_top.v
}
read_xdc D:/Sophomore/ECOP-2018/ECOP-17343155-03/CPU_imp/CPU_imp.srcs/constrs_1/new/CPU_imp.xdc
set_property used_in_implementation false [get_files D:/Sophomore/ECOP-2018/ECOP-17343155-03/CPU_imp/CPU_imp.srcs/constrs_1/new/CPU_imp.xdc]

synth_design -top imptop -part xc7a35tcpg236-1
write_checkpoint -noxdef imptop.dcp
catch { report_utilization -file imptop_utilization_synth.rpt -pb imptop_utilization_synth.pb }
